apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: horp633z2-go
  janus-idp.io/tekton: horp633z2-go
  backstage.io/kubernetes-id: horp633z2-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: horp633z2-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
